services:
  postgress:
    image: postgres:12
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dev-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://postgres:example@localhost:5432/dev-db
    depends_on:
      - postgres

volumes:
  postgres_data:
